### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
Checkout the commit messages for details.

There are no functional changes.

Thanks for this cool module! :slightly_smiling_face:

### CODE REVIEW

**Comment by Dennis-Rosenbaum** [comment]
@KristjanESPERANTO Thank you for this review, looks great!

I feel like you have some tools in place to append auto-style to the code. If that is so, could you explain this to me? I love to learn.
Maybe you could send me an e-mail at dennis.rosenbaum@outlook.com

**Comment by KristjanESPERANTO** [comment]
The introduced ESlint plugin [stylistic](https://eslint.style/) takes care of the styling. I suggest you try to apply this ESlint config to your other module. You will see if you run "npm run lint" it will show you a lot of issues. If you run "npm run lint:fix" it will fix some of them automatically. If you don't like some of the changes, you can adapt or switch of the rules in the eslint.config.mjs file. Tell me if you need help.

There are also tools for CSS (stylelint) or markdown (markdownlint) and for formatting (prettier), which in combination with ESlint have been a real game changer for my coding. I only introduced ESlint here because JavaScript is the most important part of the MagicMirror modules. The others can be introduced later.

**Comment by Dennis-Rosenbaum** [comment]
@KristjanESPERANTO 
Danke sehr! I will try this in other projects as well. I'm more of a backend developer, although I love JavaScript as well.

Maybe we could setup a small MMM Tips and Tricks section anywhere, so people get a headstart when creating their modules. What would be a good place for that?

**Comment by KristjanESPERANTO** [comment]
> I will try this in other projects as well.

:+1:  It's really worth using tools like this.

> Maybe we could setup a small MMM Tips and Tricks section anywhere ...

Nice idea. There is already [a section for module development in the official documentation](https://docs.magicmirror.builders/development/introduction.html). Before setting up something in a new location, it might be a good idea to create a new subsection there, such as "Advanced Tips and Tricks". What do you think? I only have a small amount of time to invest at the moment, but if you want to go ahead, I would be happy to assist you.

**Pull request merged**
